### ISSUE TITLE
moving ticket from root entity to child entity

### ISSUE THREAD

**Issue by udi8** [departement-maine-et-loire/transferticketentity#4]
Hi,
i have issue with the plugin - from child to root entity i can move ticket,
but from root to child i cannot its not showing in the drop down.

**Comment by YannickComba** [comment]
Hello,
 
This plugin requires at least one active group on each entity on which we want to make transfers. 
Can you confirm that your child entity does have an active group ? (Administration > Groups > Assigned to > Yes).
 
If this still don't work, in order to investigate your problem, could you please send us further information :
 - Have you reproduced the bug on another GLPI version or in another environment?
 - Could you activate debug mode, try again and send us a screenshot?
 - Could you check the server log (/var/log/XXX) and send a copy of the error (if any)?
 - Could you send us your server configuration : Windows or Linux server version, PHP, Apache, MariaDB version, etc.?
 
Thank you very much.

**Comment by udi8** [comment]
Hi,
thanks - "This plugin requires at least one active group on each entity on which we want to make transfers.
Can you confirm that your child entity does have an active group ? (Administration > Groups > Assigned to > Yes)."
it worked!
