### ISSUE TITLE
Suggestion for Enhancements in Entity and Group Visualization

### ISSUE THREAD

**Issue by ltfarm** [departement-maine-et-loire/transferticketentity#41]
Hello, 

I also have another suggestion that may be helpful. For example, if I have several entities but want to restrict the selection to only the root entity, and later define the groups within the sub-entities, these are not displayed.

Would it be possible for the selected entity to show all the groups beneath it, even if they are within sub-entities?

Best regards,

**Comment by MeLDptHelpdesk** [comment]
Hello, 

The principle of the entity is to partition the rights of GLPI objects between them.
Making all sub-entity groups selectable via the parent entity would transgress this logic.

What's more, it would mean changing the way the TransfertTicketEntity plugin works, i.e. reading the group entity to define which entity to transfer the ticket to (since the target entity is no longer selected).


Thank you for your understanding.

**Comment by ltfarm** [comment]
Agreed, thank you very much for the feedback ^^

I wish you a great week ^^"
