### ISSUE TITLE
Plugin transfer ticket suggestions

### ISSUE THREAD

**Issue by ltfarm** [departement-maine-et-loire/transferticketentity#8]
Hello,

First of all, thank you very much for the plugin. This is a demand that has been needed for a long time, and I hope that the project will eventually consume this plugin for its core.

I would like to propose some improvements that I believe are relevant to other contexts.

It would be interesting if, when there were subentities, a new dropdown menu would open, so that the list does not become too large.  The current version does not have subentities.
The justification option could be a field for request or not;
And if possible, define for which other entities tickets can be transferred.

It would also be good to have a field where we can disable or enable the option of displaying the group. This could be controlled by entity, so that some entities could opt in and others could opt out. This would make the plugin more modular.

**Comment by YannickComba** [comment]
Hello
 
Thanks for your feedback.
Some of your proposals seems to be useful.
In order to be sure to have well undestanding, could you confirm and/or complete following informations :
 
- Add option to manage Entities and Subentities with a customized menu
- Add option to make (or not) justification mandatory (per entity/subentity)
- Add option to define for which entity / subentity "Ticket transfer" is enable
- Option to display or not some groups into "Ticket transfer" menu for an authorized entity :
	- Could you explain your request because actually, only groups belonging to an enabled profile are displayed (its is the aim) ?
	- Do you want to transfer ticket directly to an entity without group ? That's it ?
 
Regarding your last post (customer service profile with more limited permissions) :
The plugin display (and authorize) only groups belonging to profile with "Ticket transfer" and "Assigned to" rights.
Could you confirm your profile is well configured ?
 
Regarding your answers and our priority, we will take them into account to a next release.
 
Regards

**Comment by ltfarm** [comment]
Good morning, sorry for the delay!

Add option to manage Entities and Subentities with custom menu
____ Response
This, for example, I have the TIC entity, within it some more sub-entities, instead of the entire list appearing, open another menu with the child entities. It would be interesting to exclude the root entity.

- Add option to make (or not) justification mandatory (per entity/sub-entity)
____ Response
---- Yes, because in our tests we received feedback from areas that would not choose to add this routine.

Option to display or not some groups in the "Ticket transfer" menu to an authorized entity:
Could you explain your request because actually only groups belonging to an enabled profile are displayed (that's the goal)?
Do you want to transfer a ticket directly to an entity without a group? And that ?
____ Response
Perhaps having an option that allows all groups to appear or determining a single group in which every ticket is forwarded, in this sense, the groups option does not need to appear.
Because among the groups contained in the entity, one is responsible for receiving tickets.

**Comment by YannickComba** [comment]
Hello,
 
Thanks for your feedback, most of your suggestion will be added in the new version 1.1.
This version is currently under test, your issue will be closed at its the release.
If you have more suggestion, you can open an issue again.
 
Regards.

**Comment by YannickComba** [comment]
Hello,

Version 1.1 is now available, thanks for your contribution.
If you have more suggestion, you can open an issue again.

Regards.
