### ISSUE TITLE
Moviment ticket between subentities

### ISSUE THREAD

**Issue by ltfarm** [departement-maine-et-loire/transferticketentity#9]
Good morning,

I carried out some more tests, I have some doubts:
# Scenario
- I have a PAI organization and several children, such as Institution > TIC, Institution > Accounting and others.
For example, technicians have permissions on child entities. There is a profile called TIC, in which the technician has permission in the TIC entity.

#Problem
When transferring the ticket to another institution (for example, the accounting department), it didn't work.

In this case, should the technician be at the PAI entity? This is a problem, reducing the possibility of encapsulating permissions and access.

**Comment by YannickComba** [comment]
Hello,
 
In order for this plugin to work, the technician must belong to the group assigned to the ticket. Otherwise, he must assign it to himself, there's no need for him to be in the same entity.
In the new version 1.1, you will also need to configure your settings in Administration > Entity.

In the new version, I can confirm you that the technician don't need to be in the same entity, if it happen in this one, it's a bug.
 
This issue will be closed at the release of 1.1, you can open an issue again if there's a problem with this plugin.
 
Regards.
